export const LOADING_REQUEST = 'LOADING_REQUEST';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const GET_NETWORK_STATUS_SUCCESS = 'GET_NETWORK_STATUS_SUCCESS';

export const GET_TOKEN_SUCCESS = 'GET_TOKEN_SUCCESS';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_SUCCESS = 'GET_USER_DETAILS_SUCCESS';
export const GET_USER_DETAILS_FAILURE = 'GET_USER_DETAILS_FAILURE';

export const GET_USERS_DETAILS_REQUEST = 'GET_USERS_DETAILS_REQUEST';
export const GET_USERS_DETAILS_SUCCESS = 'GET_USERS_DETAILS_SUCCESS';
export const GET_USERS_DETAILS_FAILURE = 'GET_USERS_DETAILS_FAILURE';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS';
export const UPDATE_USER_DETAILS_FAILURE = 'UPDATE_USER_DETAILS_FAILURE';

export const USER_REPORT_REQUEST = 'USER_REPORT_REQUEST';
export const USER_REPORT_SUCCESS = 'USER_REPORT_SUCCESS';
export const USER_REPORT_FAILURE = 'USER_REPORT_FAILURE';

export const GET_USER_LOCATION_BOTH_REQUESTS_REQUEST = 'GET_USER_LOCATION_BOTH_REQUESTS_REQUEST';
export const GET_USER_LOCATION_BOTH_REQUESTS_SUCCESS = 'GET_USER_LOCATION_BOTH_REQUESTS_SUCCESS';
export const GET_USER_LOCATION_BOTH_REQUESTS_FAILURE = 'GET_USER_LOCATION_BOTH_REQUESTS_FAILURE';

export const LOGOUT = 'LOGOUT';

// Add more action types as needed
